# Procedure

CREATE PROCEDURE insert_drugs(
    IN DRUG_ID INT,
    IN DRUG_NAME VARCHAR(100),
    IN DRUGS_DISEASE_TREATED VARCHAR(100),
    IN METHOD_OF_ADMIN VARCHAR(100),
    IN DRUG_TYPE VARCHAR(100),
    IN DRUG_ACTIVE_INGREDIENT VARCHAR(100)
)

BEGIN
    INSERT INTO DRUGS VALUES (DRUG_ID, DRUG_NAME, DRUGS_DISEASE_TREATED, METHOD_OF_ADMIN, DRUG_TYPE, DRUG_ACTIVE_INGREDIENT);
END;

call insert_drugs(
    12,
    "Proair_4",
    "Asthma",
    "Orally inhaled",
    "Branded",
    "Insulin Glargine"
);

SELECT * FROM DRUGS;

# Trigger

DELIMITER ||
CREATE TRIGGER Prescription_trigger AFTER INSERT ON PRESCRIPTION_LINES
    FOR EACH ROW
    BEGIN
        INSERT INTO PRICE_QUANT_TOTAL VALUES (NEW.RX_LINE_ID, NEW.RX_LINE_PRICE, NEW.RX_LINE_QUANTITY, NEW.RX_LINE_PRICE*NEW.RX_LINE_QUANTITY);
    END
||

INSERT INTO PRESCRIPTION_LINES(RX_ID, DRUG_ID, RX_LINE_PRICE, RX_LINE_QUANTITY) VALUES(1,7,200,30);

SELECT * FROM PRICE_QUANT_TOTAL;