SELECT P.PAT_AGE AS 'Patient\'s Age', DP.POL_PREMIUM AS 'Policy Premiums',
CASE
	WHEN DP.POL_PREMIUM > 1200 THEN 'High'
    WHEN DP.POL_PREMIUM > 800 AND DP.POL_PREMIUM <= 1200 THEN 'Medium'
    WHEN DP.POL_PREMIUM <= 800 THEN 'Low'
END AS 'Premium Profile'
FROM PATIENT AS P
INNER JOIN INSURANCE AS I ON P.POL_ID = I.POL_ID
INNER JOIN DUR_PREMIUM AS DP ON I.POL_ID = DP.POL_ID;


SELECT P.PAT_ID AS 'Patient IDs', DR.DRUGS_DISEASE_TREATED AS 'Diseases'
FROM PATIENT AS P
INNER JOIN PRESCRIPTION AS PRES ON P.PAT_ID = PRES.PAT_ID
INNER JOIN PRESCRIPTION_LINES AS PRES_LINE ON PRES.RX_ID = PRES_LINE.RX_ID
INNER JOIN DRUGS AS DR ON PRES_LINE.DRUG_ID = DR.DRUG_ID;


SELECT DISTINCT METHOD_OF_ADMIN, COUNT(METHOD_OF_ADMIN)
FROM DRUGS
NATURAL JOIN PRESCRIPTION_LINES
GROUP BY METHOD_OF_ADMIN
ORDER BY COUNT(RX_LINE_PRICE) DESC
LIMIT 1;
