# Problem 1

```{r}
library(doParallel)
library(parallel)
library(pracma)
```

```{r}
time_consuming_func <- function(){
  Sys.sleep(5)
}
```

## Normal Computation

```{r}
start_time <- Sys.time()
result = foreach(1:8) %do% time_consuming_func()
t1 <- Sys.time() - start_time
sprintf("t1: %f sec", t1)
```

## Embarrasingly Parallel Computation

```{r}
n <- 8

muCluster <- makeCluster(detectCores(), type = 'PSOCK')
registerDoParallel(muCluster)

start_time_2 <- Sys.time()
result = foreach(1:n) %dopar% time_consuming_func()
tp <- Sys.time() - start_time_2

stopCluster(muCluster)

sprintf("tp: %f sec", tp)
```


```{r}
speedup <- function(t1, tp){
  return(as.double(t1)/as.double(tp))
}
efficiency <- function(speedup){
  return((speedup/detectCores()) * 100)
}

speedup_ <- speedup(t1, tp)
efficiency_ <- efficiency(speedup_)

sprintf("speedup: %f", speedup_)
sprintf("efficiency: %f", efficiency_)
```

## For different number of n

### for n = 8
```{r}
n1 <- 8

muCluster <- makeCluster(detectCores(), type = 'PSOCK')
registerDoParallel(muCluster)

start_time_2 <- Sys.time()
result = foreach(1:n1) %dopar% time_consuming_func()
tp1 <- Sys.time() - start_time_2

stopCluster(muCluster)
tp1

speedup_1 <- speedup(t1, tp1)
efficiency_1 <- efficiency(speedup_1)

sprintf("for n: %d, speedup: %f, efficiency: %f", n1, speedup_1, efficiency_1)
```

### for n = 54
```{r}
n2 <- 54

muCluster <- makeCluster(detectCores(), type = 'PSOCK')
registerDoParallel(muCluster)

start_time_3 <- Sys.time()
result = foreach(1:n2) %dopar% time_consuming_func()
tp2 <- Sys.time() - start_time_3

stopCluster(muCluster)
tp2

speedup_2 <- speedup(n2*5, tp2)
efficiency_2 <- efficiency(speedup_2)

sprintf("for n: %d, speedup: %f, efficiency: %f", n2, speedup_2, efficiency_2)
```

### for n = 400
```{r}
n3 <- 400

muCluster <- makeCluster(detectCores(), type = 'PSOCK')
registerDoParallel(muCluster)

start_time_4 <- Sys.time()
result = foreach(1:n3) %dopar% time_consuming_func()
tp3 <- Sys.time() - start_time_4

stopCluster(muCluster)
tp3

speedup_3 <- speedup(n3*5, tp3*60)
efficiency_3 <- efficiency(speedup_3)

sprintf("for n: %d, speedup: %f, efficiency: %f", n3, speedup_3, efficiency_3)
```

