-- MySQL Script generated by MySQL Workbench
-- Sat Feb  4 22:24:24 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`DEPT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DEPT` (
  `DCode` INT NOT NULL,
  `DName` VARCHAR(45) NOT NULL,
  `DOffice` VARCHAR(45) NULL,
  `DPhone` INT NULL,
  `CollegeName` VARCHAR(45) NOT NULL,
  `Chair` INT NOT NULL,
  `CStartDate` DATETIME NULL,
  PRIMARY KEY (`DCode`, `CollegeName`, `DName`, `Chair`),
  INDEX `fk_DEPT_COLLEGE1_idx` (`CollegeName` ASC),
  INDEX `fk_DEPT_INSTRUCTOR1_idx` (`Chair` ASC),
  CONSTRAINT `fk_DEPT_COLLEGE1`
    FOREIGN KEY (`CollegeName`)
    REFERENCES `mydb`.`COLLEGE` (`CName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEPT_INSTRUCTOR1`
    FOREIGN KEY (`Chair`)
    REFERENCES `mydb`.`INSTRUCTOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`INSTRUCTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`INSTRUCTOR` (
  `Id` INT NOT NULL,
  `IName` VARCHAR(45) NOT NULL,
  `IOffice` VARCHAR(45) NULL,
  `IPhone` INT NULL,
  `Rank` INT NULL,
  `DepartmentCode` INT NOT NULL,
  `CName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`, `DepartmentCode`, `CName`),
  INDEX `fk_INSTRUCTOR_COLLEGE_idx` (`CName` ASC),
  INDEX `fk_INSTRUCTOR_DEPT1_idx` (`DepartmentCode` ASC),
  CONSTRAINT `fk_INSTRUCTOR_COLLEGE`
    FOREIGN KEY (`CName`)
    REFERENCES `mydb`.`COLLEGE` (`CName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INSTRUCTOR_DEPT1`
    FOREIGN KEY (`DepartmentCode`)
    REFERENCES `mydb`.`DEPT` (`DCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COLLEGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COLLEGE` (
  `CName` VARCHAR(45) NOT NULL,
  `COffice` VARCHAR(45) NULL,
  `CPhone` INT NULL,
  `DeanId` INT NULL,
  PRIMARY KEY (`CName`),
  INDEX `fk_COLLEGE_INSTRUCTOR1_idx` (`DeanId` ASC),
  CONSTRAINT `fk_COLLEGE_INSTRUCTOR1`
    FOREIGN KEY (`DeanId`)
    REFERENCES `mydb`.`INSTRUCTOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`STUDENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`STUDENT` (
  `SId` INT NOT NULL,
  `FName` VARCHAR(45) NOT NULL,
  `MName` VARCHAR(45) NOT NULL,
  `LName` VARCHAR(45) NOT NULL,
  `DOB` DATETIME NOT NULL,
  `Addr` VARCHAR(100) NOT NULL,
  `Phone` INT NULL,
  `Major` VARCHAR(60) NULL,
  `DepartmentId` INT NOT NULL,
  PRIMARY KEY (`SId`, `DepartmentId`),
  INDEX `fk_STUDENT_DEPT1_idx` (`DepartmentId` ASC),
  CONSTRAINT `fk_STUDENT_DEPT1`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `mydb`.`DEPT` (`DCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `CCode` INT NOT NULL,
  `CoName` VARCHAR(45) NOT NULL,
  `Credits` INT NULL,
  `Level` INT NULL,
  `CDesc` TEXT(1024) NULL,
  `DepartmentId` INT NOT NULL,
  PRIMARY KEY (`CCode`, `DepartmentId`),
  INDEX `fk_COURSE_DEPT1_idx` (`DepartmentId` ASC),
  CONSTRAINT `fk_COURSE_DEPT1`
    FOREIGN KEY (`DepartmentId`)
    REFERENCES `mydb`.`DEPT` (`DCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SECTION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SECTION` (
  `Secld` INT NOT NULL,
  `SecNo` INT NULL,
  `Sem` INT NULL,
  `Year` VARCHAR(45) NULL,
  `CRoom` VARCHAR(45) NULL,
  `DaysTime` DATETIME NULL,
  `InstructorId` INT NOT NULL,
  `CourceId` INT NOT NULL,
  PRIMARY KEY (`Secld`, `CourceId`, `InstructorId`),
  INDEX `fk_SECTION_INSTRUCTOR1_idx` (`InstructorId` ASC),
  INDEX `fk_SECTION_COURSE1_idx` (`CourceId` ASC),
  CONSTRAINT `fk_SECTION_INSTRUCTOR1`
    FOREIGN KEY (`InstructorId`)
    REFERENCES `mydb`.`INSTRUCTOR` (`Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SECTION_COURSE1`
    FOREIGN KEY (`CourceId`)
    REFERENCES `mydb`.`COURSE` (`CCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GRADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GRADE` (
  `id` INT NOT NULL,
  `StudentId` INT NOT NULL,
  `SectionId` INT NOT NULL,
  `grade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `SectionId`, `StudentId`),
  INDEX `fk_STUDENT_SECTION_STUDENT1_idx` (`StudentId` ASC),
  INDEX `fk_STUDENT_SECTION_SECTION1_idx` (`SectionId` ASC),
  CONSTRAINT `fk_STUDENT_SECTION_STUDENT1`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mydb`.`STUDENT` (`SId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STUDENT_SECTION_SECTION1`
    FOREIGN KEY (`SectionId`)
    REFERENCES `mydb`.`SECTION` (`Secld`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
