version: '3'

services:
  db:
    image: mysql:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password

volumes:
  dbdata:
