CREATE PROCEDURE insert_drugs(
    IN DRUG_ID INT,
    IN DRUG_NAME VARCHAR(100),
    IN DRUGS_DISEASE_TREATED VARCHAR(100),
    IN METHOD_OF_ADMIN VARCHAR(100),
    IN DRUG_TYPE VARCHAR(100),
    IN DRUG_ACTIVE_INGREDIENT VARCHAR(100)
)

BEGIN
    INSERT INTO DRUGS VALUES (DRUG_ID, DRUG_NAME, DRUGS_DISEASE_TREATED, METHOD_OF_ADMIN, DRUG_TYPE, DRUG_ACTIVE_INGREDIENT);
END;

call insert_drugs(
    12,
    "Proair_4",
    "Asthma",
    "Orally inhaled",
    "Branded",
    "Insulin Glargine"
);

SELECT * FROM DRUGS;