DELIMITER ||
CREATE TRIGGER Pres_Trg_2 AFTER INSERT ON PRESCRIPTION_LINES
	FOR EACH ROW
	BEGIN
		DECLARE rx_line_subtotal FLOAT;
        DECLARE rx_id_count INT;

        INSERT INTO PRICE_QUANT_TOTAL VALUES (NEW.RX_LINE_ID, NEW.RX_LINE_PRICE, NEW.RX_LINE_QUANTITY, NEW.RX_LINE_PRICE*NEW.RX_LINE_QUANTITY);

        SELECT SUM(B.RX_LINE_TOTAL) INTO rx_line_subtotal
        FROM PRESCRIPTION_LINES AS A INNER JOIN PRICE_QUANT_TOTAL AS B ON A.RX_LINE_ID = B.RX_LINE_ID
        WHERE A.RX_ID = NEW.RX_ID
        GROUP BY A.RX_ID;

        UPDATE PRESCRIPTION SET RX_SUBTOTAL = rx_line_subtotal WHERE RX_ID = NEW.RX_ID;

        SELECT COUNT(*) INTO rx_id_count FROM SUBTOT_TAX_TOT as stt WHERE stt.RX_ID = new.RX_ID;

        IF rx_id_count>0 THEN
			UPDATE SUBTOT_TAX_TOT SET RX_SUBTOTAL = RX_SUBTOTAL + rx_line_subtotal WHERE RX_ID = new.RX_ID;
            UPDATE SUBTOT_TAX_TOT SET RX_TOTAL = RX_TOTAL + (1.0625*rx_line_subtotal) WHERE RX_ID = new.RX_ID;
        ELSE
			INSERT INTO SUBTOT_TAX_TOT VALUES (NEW.RX_ID, rx_line_subtotal, 6.25, 1.0625*rx_line_subtotal);
		END IF;
	END
||

SELECT * FROM DUR_PREMIUM;