DELIMITER ||
CREATE TRIGGER Prescription_trigger AFTER INSERT ON PRESCRIPTION_LINES
    FOR EACH ROW
    BEGIN
        INSERT INTO PRICE_QUANT_TOTAL VALUES (NEW.RX_LINE_ID, NEW.RX_LINE_PRICE, NEW.RX_LINE_QUANTITY, NEW.RX_LINE_PRICE*NEW.RX_LINE_QUANTITY);
    END
||

INSERT INTO PRESCRIPTION_LINES(RX_ID, DRUG_ID, RX_LINE_PRICE, RX_LINE_QUANTITY) VALUES(1,7,200,30);

SELECT * FROM PRICE_QUANT_TOTAL;